server {
    listen 80;
    server_name localhost;

    # The Health Check endpoint
    location /checkhealth {
        access_log off;
        add_header 'Content-Type' 'text/plain';
        return 200 "OK";
    }

    # Your Flutter Web App
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
